### ISSUE TITLE
Headers are not exported when there is no response content

### ISSUE THREAD

**Issue by jacobshirley** [drwpow/openapi-typescript#1262] opened 2023-07-30 19:45 UTC
**Description**

When there is no response content, header types are not exported. I believe this is caused by these lines: https://github.com/drwpow/openapi-typescript/blob/efbc4498ef04ff303ab0804451a701acd7fc5196/packages/openapi-typescript/src/transform/response-object.ts#L13-L14

This affects HEAD requests

```
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.3.9`                      |
| Node.js              | `20.4.0`                      |
| OS + version         | `MacOS Ventura` |

**Reproduction**

If run openapi-typescript on this example spec: https://gist.github.com/jacobshirley/96f18b0244d927146ef66a09c6110594 - it will not output types for X-Document-Reference. It will output 'never' for the 200 response.

**Expected result**

It should output the X-Document-Reference type

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment] 2023-07-31 20:02
This is a bug, but is a duplicate of #1109, so I’ll close this in favor of that one.

**Closed by drwpow** 2023-07-31 20:02 UTC
Labels: bug, openapi-ts
