### ISSUE TITLE
generate ts file SyntaxError

### ISSUE THREAD

**Issue by liangskyli** [drwpow/openapi-typescript#1000] opened 2022-11-20 07:16 UTC
**Description**

generate ts file SyntaxError

my openapi3 json file
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "bff to openapi3",
    "version": "1.0.0"
  },
  "paths": {
    "/v1/getUser2": {
      "get": {
        "operationId": "UserController.getUser2.DjHhjSamaD",
        "tags": ["User"],
        "summary": "",
        "description": "UserController.getUser2",
        "parameters": [
          {
            "in": "query",
            "name": "param1",
            "description": "",
            "required": false,
            "schema": {
              "type": "number"
            }
          },
          {
            "in": "query",
            "name": "param2",
            "description": "",
            "required": false,
            "schema": {
              "type": "object",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "$ref": "#/components/schemas/IUserWithId"
                }
              ]
            }
          },
          {
            "in": "query",
            "name": "param3",
            "description": "",
            "required": false,
            "schema": {
              "type": "object",
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "$ref": "#/components/schemas/IUserWithName"
                }
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {}
              }
            },
            "description": "Successful response"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "IUserWithId": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/Partial<Pick<IUser,\"id\">>"
          },
          {
            "type": "string"
          }
        ]
      },
      "Partial<Pick<IUser,\"id\">>": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          }
        }
      },
      "IUserWithName": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        },
        "required": ["name"]
      },
      "IUser": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "name": {
            "type": "string"
          }
        },
        "required": ["id"]
      }
    }
  }
}

```

generate ts file
```
  
/** Type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/v1/getUser2": {
    /** @description UserController.getUser2 */
    get: operations["UserController.getUser2.DjHhjSamaD"];
  };
}

export interface components {
  schemas: {
    IUserWithId: components["schemas"]["Partial<Pick<IUser,\\"id\\">>"] | string;
    "Partial<Pick<IUser,\"id\">>": {
      id?: number;
    };
    IUserWithName: {
      name: string;
    };
    IUser: {
      id: number;
      name?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  "UserController.getUser2.DjHhjSamaD": {
    /** @description UserController.getUser2 */
    parameters?: {
      query?: {
        param1?: number;
        param2?: string | components["schemas"]["IUserWithId"];
        param3?: string | components["schemas"]["IUserWithName"];
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
}

```
SyntaxError in this, you can use openapi.json file to generate ts file

```
IUserWithId: components["schemas"]["Partial<Pick<IUser,\\"id\\">>"] | string;
``` 
The correct one should be
```
IUserWithId: components["schemas"]["Partial<Pick<IUser,\"id\">>"] | string;
```

| Name                 | Version                      |
|:---------------------|:-----------------------------|
| `openapi-typescript` | `6.0.3`                      |
| Node.js              | `14.19.3`                      |
| OS + version         | `macOS 12` |

**Comment by mitchell-merry** [comment] 2023-04-09 23:51
Duplicate of #915

**Closed by mitchell-merry** 2023-04-09 23:51 UTC
Labels: duplicate
