### ISSUE TITLE
openapiTS & $ref

### ISSUE THREAD

**Issue by kondo97** [drwpow/openapi-typescript#954] opened 2022-10-16 12:47 UTC
Can I use "$ref" in "openapiTS".

my code 
``` typescript
// docs.index.yml
openapi: 3.0.0
info:
  title: XXX
servers:
- url: /
paths:
  /hoge:
    $ref: ./paths/hoge#/hoge

// formatter.js
import * as fs from "fs";
import openapiTS from "openapi-typescript";
import yaml from "js-yaml";

const main = async () => {
  const yamlDoc = fs.readFileSync("docs/index.yml", "utf-8").toString();
  const schema = yaml.load(yamlDoc)

  const output = await openapiTS(schema, {
    formatter(node) {
      if (node.format === "date-time") {
        return "Date"; 
      }
    }
  })
  console.log(output)
}

main()
```

error occured
``` typescript
UnhandledPromiseRejectionWarning: Error: Can’t load URL "./paths/hoge.yml" from dynamic JSON. Load this schema from a URL instead.
```

this is successful
``` typescript
// docs.index.yml
openapi: 3.0.0
info:
  title: XXX
servers:
- url: /
paths:
  /hoge:
    $ref: ./paths/hoge#/hoge

// formatter.js
import * as fs from "fs";
import openapiTS from "openapi-typescript";
import yaml from "js-yaml";

const main = async () => {
  const output = await openapiTS("docs/index.yml", {
    formatter(node) {
      if (node.format === "date-time") {
        return "Date"; 
      }
    }
  })
  console.log(output)
}

main()
```

**Comment by drwpow** [comment] 2022-10-30 15:10
> Can I use "$ref" in "openapiTS"

Yes. The error shown is it working exactly as intended.

In your first example, `$ref: "./paths/hoge…"` is a relative URL loaded from a string you passed to openapiTS. It throws that error because how can it know where `./paths/hoge` is (also note the missing file extension—that’s usually needed)? It has no idea where you loaded that file from—if it was a local file, and if so where in your filesystem, or if it was a remote schema you got from a URL.

In order for that to work, it would have to be an absolute URL, e.g. `$ref: 'https://my-api.com/paths/hoge.yml` or even an absolute fileURL, e.g. `file:///path/to/schema/paths/hoge.yml`.

Or, in your 2nd example, you let openapiTS locate the file, so then it knows exactly where to find that relative URL.

I’m going to close this issue as this seems to be working as intended, but please open a bug report if there’s a problem resolving `$ref`s.

**Closed by drwpow** 2022-10-30 15:10 UTC
Labels: question
