### ISSUE TITLE
`TypeError: boolean true is not iterable (cannot read property Symbol(Symbol.iterator))` at 4.0.2

### ISSUE THREAD

**Issue by Charlie91** [drwpow/openapi-typescript#726] opened 2021-08-18 08:28 UTC
I have a problem on a last `4.0.2` version that I solved rolling back to `4.0.0`.

`TypeError: boolean true is not iterable (cannot read property Symbol(Symbol.iterator))`.

The error also dissapears if I change property `required` in parameter of `"type": "file"` to `false`

swagger.json
```
{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for Portal",
    "title": "Portal API",
    "version": "0.1.0"
  },
  "host": "portal.test",
  "basePath": "/api",
  "paths": {
    "/activity/transaction/{counterparty}/{transaction_number}/attachment": {
      "post": {
        "security": [
          {
            "Oauth": [
              "readaccount"
            ]
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "activity_transaction_attachment"
        ],
        "summary": "Upload attachment for the transaction",
        "operationId": "postTransactionAttachment",
        "parameters": [
          {
            "type": "file",
            "description": "The file to upload",
            "name": "file",
            "required": true,
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "Success upload an attachment for the instruction"
          },
          "default": {
            "description": "Default error",
            "schema": {
              "type": "object",
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
}
```

**Comment by eirikur-grid** [comment] 2021-08-19 13:52
I just ran into this error as well. Will give 4.0.0 a try.

**Comment by drwpow** [comment] 2021-09-30 20:57
Hm. I don’t think we know how to support `"type": "file"`. Let me push a fix for that and see if that resolves it.

**Comment by drwpow** [comment] 2021-09-30 21:14
I’m seeing an improvement to this in `4.1.0`. Please give it a try and let me know if the problem is improved.

**Comment by mmounts** [comment] 2021-11-02 18:38
Not the OP here, but I was hitting this issue in `4.0.2` today, found this issue while researching, and update to `4.1.0`. For my use case the error has now gone away and the result is as expected. Thanks!

**Comment by mitchell-merry** [comment] 2023-04-09 23:28
I believe this is fixed in version 6 as well, closing...

**Closed by mitchell-merry** 2023-04-09 23:28 UTC
Labels: bug
