### ISSUE TITLE
cannot read headers of undefined

### ISSUE THREAD

**Issue by hilleer** [drwpow/openapi-typescript#407] opened 2020-12-11 08:44 UTC
It seem like if you are using a reference like `"$ref": "./foo"` then it fails with this error.

If I use `"$ref": "foo"` then it works. I assume both should scenarios be valid :-) 

Also, the reason what and why it fails is _very_ poor. 

I managed to get this line when running the generation using node rather than CLI:

`const referencedValue = p.$ref.substr(2).split("/").reduce((value, property) => value[property], input);`.

---

It seem like it does not know how to do deal with a parameters with a reference object like:

```
/foo/bar:
  get:
     parameters:
       - $ref: components/foo.yml

**Comment by drwpow** [comment] 2020-12-31 05:05
Could this be related to #244 perhaps? Currently we don’t support external `$ref`s, so everything must be in the form of `$ref: "#/components/schemas/ParameterFoo"`, etc.

**Comment by hilleer** [comment] 2021-01-04 08:24
@drwpow I am not sure.... This is as described by the ref pointer occurring when referencing from _other files_ locally. I am not entirely sure how that works but I would be surprised if that is considered an external ref?

**Comment by drwpow** [comment] 2021-04-15 05:52
Going to consider this a duplicate of #244. Continuing discussion there.

**Closed by drwpow** 2021-04-15 05:52 UTC
Labels: enhancement, help wanted
