### ISSUE TITLE
TypeError: Cannot read property 'nullable' of undefined

### ISSUE THREAD

**Issue by ainomc** [drwpow/openapi-typescript#536] opened 2021-03-23 01:54 UTC
I'm running the npm as a pretest step in my tests:
"pretest": "openapi-typescript https://dev-e.compayname.com/swagger/Private-v1.0/swagger.json --output ./.temp/types.ts"

in the console, I'm getting:
```
✨ openapi-typescript 3.1.2
🔭 Loading spec from https://dev-e.companyname.com/swagger/Private-v1.0/swagger.json…
TypeError: Cannot read property 'nullable' of undefined
    at Object.transformSchemaObj (C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\schema.js:28:14)      
    at C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\operation.js:40:49
    at Array.forEach (<anonymous>)
    at transformRequestBodyObj (C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\operation.js:39:33)     
    at Object.transformOperationObj (C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\operation.js:27:28)
    at C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\paths.js:28:64
    at Array.forEach (<anonymous>)
    at C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\paths.js:17:79
    at Array.forEach (<anonymous>)
    at Object.transformPathsObj (C:\compayname_autotests\node_modules\openapi-typescript\dist\cjs\transform\paths.js:9:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! compayname_ui_api@1.0.0 pretest: `openapi-typescript https://dev-e.compayname.com/swagger/Private-v1.0/swagger.json --output ./.temp/types.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the compayname_ui_api@1.0.0 pretest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Name\AppData\Roaming\npm-cache\_logs\2021-03-23T01_46_08_311Z-debug.log
```

In the debug log I have:
```
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\Name\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:315:20)
22 verbose stack     at maybeClose (internal/child_process.js:1048:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
23 verbose pkgid companyname_ui_api@1.0.0

```

Swagger.json:

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "ComanyName Private API",
    "description": "ComanyName Private API",
    "termsOfService": "https://www.companyname.com/terms",
    "contact": {
      "name": "ComanyName" ,
      "url": "https://www.companyname.com/enterprise",
    },
    "license": {
      "name": "Use under license",
      "url": "https://www.companyname.com/terms"
    },
    "version": "v1.0"
```

Accessing open swagger API with the command:
```
npx openapi-typescript https://enterprise.skyhive.io/swagger/v1.0/swagger.json --output test-prod-api.ts
```
 lead to the same issue - TypeError: Cannot read property 'nullable' of undefined

1 info using npm@7.6.3
2 info using node@v14.16.0

Could you say, what can be wrong? How to fix it?

**Comment by ainomc** [comment] 2021-03-23 17:05
@drwpow hey! Could you take a look?

**Comment by drwpow** [comment] 2021-03-23 18:26
Hello! Are you able to provide your schema that‘s failing? And can you verify that your schema is 100% valid to the OpenAPI format? If it is valid, we may have a bug here. But any detail you can provide would be helpful.

**Comment by judehunter** [comment] 2021-04-03 16:47
just stumbled upon this as well
my schema is generated by the `routing-controllers-openapi` lib

**Comment by judehunter** [comment] 2021-04-03 16:57
@drwpow I've tried stripping the schema to the bare minimum (just one operation) and the problem disappeared, but I wasn't able to find what the culprit was exactly.
Here's the full schema (I believe it's valid?):
https://pastebin.com/yq3vmW7P

Also, the example in the readme (`npx openapi-typescript https://petstore.swagger.io/v2/swagger.json --output petstore.ts`) does work for me.

**Comment by drwpow** [comment] 2021-04-05 17:12
Thanks for providing more detail! I will take a look.

**Comment by Crazymax11** [comment] 2021-04-13 03:29
in my case the problem was empty response schema for `application/pdf` content.

It would be nice to see some helpful info related to TypeError. Something like
- the problem has occured while trying to parse paths."/api/endpoint".post.responses.200, check it!
- check your swagger schema via validator (link to validator)

**Comment by drwpow** [comment] 2021-04-15 05:19
@judehunter so just uncovered a bug! Thanks for that. The bug in question was caused by this line:

```yaml
      responses:
        '200':
          content:
            application/json: {}
```

In this case we were throwing an error if there was no `schema`. But you’re correct that this should be valid. Pushed a fix here: https://github.com/drwpow/openapi-typescript/pull/565

**Comment by drwpow** [comment] 2021-04-15 05:26
> in my case the problem was empty response schema for `application/pdf` content.

@Crazymax11 do you have a URL for that? If I try and load content from a server that returns that contentType, this is the error message I get:

```
❌ Error: Unknown format: "application/pdf". Only YAML or JSON supported.
```

**Comment by drwpow** [comment] 2021-04-15 05:31
I’ve resolved the issue in @judehunter’s reported schema, but if I’ve missed any other cases please let me know!

**Closed** 2021-04-15 05:30 UTC
Labels: bug

**Comment by ainomc** [comment] 2021-04-29 23:59
@drwpow hey!
Thank you for the fix!

I've talked to developers and they admitted that we have issues in the json schema, but they can't change anything, because it leads to changes on related systems as well.

Is any way, to optional ignore some of API methods inside the schema? If not, is it difficult to implement something like this?

**Comment by ainomc** [comment] 2021-05-03 23:42
@drwpow ping :)
