### ISSUE TITLE
Simple api spec results in invalid typescript

### ISSUE THREAD

**Issue by pgsandstrom** [drwpow/openapi-typescript#1275] opened 2023-08-07 11:37 UTC
**Description**

I have a small example of a valid openapi spec as a json file. When bundling it with openapi-typescript, the generated typescript is invalid.

The input is as following:

```
{
  "openapi": "3.0.2",
  "info": { "title": "foo", "version": "1.0" },
  "servers": [{ "url": "http://localhost:9005", "description": "dev environment" }],
  "paths": {
    "/lame": {
      "get": {
        "summary": "sum",
        "operationid": "foo",
        "responses": {
          "200": {
            "description": "desc",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "somestring": {
                        "type": "string",
                        "description": "the id number of a specific invoice"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/someurl": {
      "post": {
        "summary": "sum",
        "operationid": "bar",
        "responses": {
          "200": {
            "description": "desc",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "invoices": {
                      "type": "array",
                      "items": {
                        "$ref": "#/paths/~1lame/get/responses/200/content/application~1json/schema/items"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

```

I run `const output = await openapiTS(input)`.

The output is as following:

```
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/lame": {
    /** sum */
    get: operations["foo"]
  }
  "/someurl": {
    /** sum */
    post: operations["bar"]
  }
}

export type webhooks = Record<string, never>

export type components = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** sum */
  foo: {
    responses: {
      /** @description desc */
      200: {
        content: {
          "application/json": {
            /** @description The id number of a specific invoice */
            someString?: string
          }[]
        }
      }
    }
  }
  /** sum */
  bar: {
    responses: {
      /** @description desc */
      200: {
        content: {
          "application/json": {
            invoices?: paths["/lame"]["get"]["responses"]["200"]["content"]["application/json"]["schema"]["items"][]
          }
        }
      }
    }
  }
}


```

To get the typescript to compile I would have to remove `["schema"]["items"][]` from the last row.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `6.4.0`                      |
| Node.js              | `v18.16.1`                      |
| OS + version         | `macOS 13` |

**Reproduction**

I hope input/output is sufficient. I could upload a small sample project if it would help.

**Checklist**

- [X] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [X] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/CONTRIBUTING.md))

The redocly validator did give some hints, but they were not relevant and I ignored them to keep the example small. The api does pass validators such as https://apitools.dev/swagger-parser/online/

**Comment by drwpow** [comment] 2023-08-20 00:40
This is a duplicate of #956. The underlying issue is this library doesn’t currently support referencing schema properties like you’re doing. I know some tools support it; some don’t. I’m a little fuzzy on whether or not this is technically valid spec or not. But we haven’t made a decision yet whether or not to add this feature. Either way, tracking in #956.

As a temporary workaround, move all `$ref`s either into the Components object, or move them to external files (referencing partial schemas works just fine)

**Closed by drwpow** 2023-08-20 00:40 UTC
Labels: bug, help wanted, good first issue, openapi-ts

**Comment by drwpow** [comment] 2023-08-21 00:57
Update: the newest version lets you declare JSONSchema $defs on any schema object, as well as on the root. This is the recommended way to reference subschemas without making them an explicitly separate component, etc.
