### ISSUE TITLE
Add an option to generate type aliases for schemas

### ISSUE THREAD

**Issue by tgross35** [drwpow/openapi-typescript#1543] opened 2024-02-15 23:18 UTC
**Description**

Schemas are probably the closest representation of TS types and are reused in similar ways. It is somewhat awkward to refer to them using their string paths all the time.

**Proposal**

Add a flag like `--generate-schema-type-aliases` that will generate type aliases for schema types. For example, with the below:

```js
export interface components {
    schemas: {
        /** About */
        About: {
            name: string;
            version: string;
            /** Format: date */
            build_date: string;
        };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
```

With the flag, there would be a new alias that could be directly imported:

```js
type About = components["schemas"]["About"];
```

**Checklist**

- [ ] I’m willing to open a PR for this (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by drwpow** [comment] 2024-02-15 23:33
This has been proposed before, and there are limitations to this. Chiefly, OpenAPI lets you use invalid characters that aren’t valid identifiers, and handling conflicts is tricky (`Object.foo` and `Object-foo` are 2 valid schema object names that shouldn’t conflict). So yes, agreed—it’s slightly-verbose for consumers of schemas with IDs that don’t use special characters. But unusable for many schemas that do.

Anyways, this is a dupe of the issue #1414, and is being built out in a PR here (#1260), so please add additional thoughts/comments there to track this.

**Closed by drwpow** 2024-02-15 23:33 UTC
Labels: enhancement, help wanted, openapi-ts

**Comment by tgross35** [comment] 2024-02-15 23:45
Thanks for the quick response, sorry I missed those!
