### ISSUE TITLE
Support 'additionalProperties' 

### ISSUE THREAD

**Issue by cjpete** [drwpow/openapi-typescript#311] opened 2020-08-18 15:07 UTC
https://swagger.io/docs/specification/data-models/dictionaries/

```
"ItemDto": {
  ...
},
"CollectionDto": {
    "type": "object",
    "properties": {
      "tables": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ItemDto"
          }
        }
      }
    },
    "title": "CollectionDto"
},
```

This outputs an invalid type interface like this:

```
CollectionDto: { tables?: { [key: string]: array } };
```

Whereas it should be:

```
CollectionDto: { tables?: { [key: string]: definitions["ItemDto"][] } };
```

**Comment by cjpete** [comment] 2020-08-18 15:17
Here's a patchfile for anyone else who needs this. I'll put a PR together too.

```
diff --git a/node_modules/@manifoldco/swagger-to-ts/dist-node/index.js b/node_modules/@manifoldco/swagger-to-ts/dist-node/index.js
index ff14209..3f5f525 100644
--- a/node_modules/@manifoldco/swagger-to-ts/dist-node/index.js
+++ b/node_modules/@manifoldco/swagger-to-ts/dist-node/index.js
@@ -216,7 +216,17 @@ function generateTypesV2(schema, options) {
           let properties = createKeys(node.properties || {}, node.required);
 
           if (node.additionalProperties) {
-            properties += `[key: string]: ${nodeType(node.additionalProperties) || "any"};\n`;
+            const nodeTypeOfAdditionalProps = nodeType(node.additionalProperties)
+            if (nodeTypeOfAdditionalProps === 'array') {
+              const nodeTypeOfAdditionalItems = nodeType(node.additionalProperties.items)
+              if (nodeTypeOfAdditionalItems === 'ref') {
+                properties += `[key: string]: ${tsArrayOf(transform(node.additionalProperties.items))};\n`;
+              } else {
+                properties += `[key: string]: ${nodeTypeOfAdditionalItems || "any"};\n`;
+              }
+            } else {
+              properties += `[key: string]: ${nodeTypeOfAdditionalProps || "any"};\n`;
+            }
           }
 
           return tsIntersectionOf([...(node.allOf ? node.allOf.map(transform) : []), ...(properties ? [`{ ${properties} }`] : [])]);
@@ -307,7 +317,6 @@ function generateTypesV3(schema, options) {
         }
     }
 
-    return "";
   }
 
   function createKeys(obj, required) {
```

**Comment by zach-waggoner** [comment] 2020-09-11 02:56
I have a similar problem which seems related. Given the schema

```yaml
components:
  schemas:
    Example:
      type: object
      properties:
        dictionary:
          type: object
          additionalProperties:
            type: number
            nullable: true
      required:
        - dictionary
```

swagger-to-ts generates

```ts
export interface components {
  schemas: {
    Example: {
      dictionary: { [key: string]: number };
    };
  };
}
```

whereas it should be

```ts
export interface components {
  schemas: {
    Example: {
      dictionary: { [key: string]: number | null };
    };
  };
}
```

**Comment by andrew-farries** [comment] 2020-09-18 15:41
Here's another minimal reproduction for the lack of `additionalProperties` support. Given this part of an API spec:

```json
  "components": {
    "schemas": {
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": {
          "type": "object",
          "additionalProperties": false
        }
      }
    }
  }
```

`swagger-to-ts` generates:

```typescript
export interface components {
  schemas: {
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
      [key: string]: { [key: string]: any };
    };
  };
}
```

which has an invalid index signature. The index signature needs to be:

```typescript
[key: string]: { [key: string]: any } | string | null | number;
```

**Comment by bitsofinfo** [comment] 2020-09-22 15:27
#324 related?

**Comment by bitsofinfo** [comment] 2020-09-22 15:29
I see this is in #294.... how can I make use of this?

**Comment by Adamantinu** [comment] 2020-10-21 11:05
Would be great to be fixed since the .net core feature of the ProblemDetails runs into this problem when documented via the ProducesResponseTypeAttribute

**Comment by drwpow** [comment] 2021-01-11 16:50
Just improved support for `additionalProperties` in #442 but will be taking a look at this next to see if I missed any cases (more than likely I did)

**Comment by drwpow** [comment] 2021-04-15 06:15
Support for additionalProperties has been greatly improved in this library since this issue was filed. I’m going to close this, but if there are any cases I’ve missed please let me know, either in this issue or by opening a new one with a specific schema to test.

**Closed by drwpow** 2021-04-15 06:15 UTC
Labels: bug, help wanted
